export const GENRES_WORK = [
  "Film",
  "Ad",
  "Videogame",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Drama",
  "Art",
  "Comedy",
  "Action",
];

export const GENRES_PIECES = [
  "Piano",
  "Orchestral",
  "Vintage",
  "Electronic",
  "Folkish",
  "Lyrics",
  "No lyrics",
  "Epic",
  "Easy",
  "Eccentric",
  "Intense",
  "Smooth",
  "Translucent",
  "Vibrant",
  "Misty",
  "Dark",
];

export const PIECES = [
  {
    name: "I Thought It Would Be Fun",
    tags: ["Piano", "Orchestral", "Vintage"],
    imageSrc: "/images/track1.webp",
    audioSrc: "/audio/Theory-of-Light-Master.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Worn Out",
    tags: ["Piano", "Electronic"],
    imageSrc: "/images/track2.webp",
    audioSrc: "/audio/Theory-of-Light-Master.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Threat Serenade",
    tags: ["Dark", "Vibrant", "Misty"],
    imageSrc: "/images/track3.webp",
    audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "The End of Patience",
    tags: ["Vibrant", "Misty", "Epic"],
    imageSrc: "/images/track4.webp",
    audioSrc: "/audio/Theory-of-Light-Master.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Revival of the Unknown",
    tags: ["Folkish", "Lyrics", "No lyrics", "Epic", "Easy"],
    imageSrc: "/images/track1.webp",
    audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Power Drip",
    tags: ["Epic", "Easy", "Eccentric"],
    imageSrc: "/images/track2.webp",
    audioSrc: "/audio/Theory-of-Light-Master.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Journey Around the Fortune",
    tags: ["Translucent", "Vibrant"],
    imageSrc: "/images/track3.webp",
    audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Going Far Away",
    tags: ["Intense", "Smooth"],
    imageSrc: "/images/track4.webp",
    audioSrc: "/audio/Theory-of-Light-Master.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Full of Wondering",
    tags: ["Folkish", "Lyrics", "No lyrics"],
    imageSrc: "/images/track1.webp",
    audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Cats and Dogs",
    tags: ["Vintage", "Electronic", "Intense", "Smooth"],
    imageSrc: "/images/track2.webp",
    audioSrc: "/audio/Theory-of-Light-Master.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
];
