export const GENRES_PROJECTS = [
  "Film",
  "Ad",
  "Game",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Drama",
  "Art",
  "Comedy",
  "Action",
];

export const GENRES_PIECES = [
  "Piano",
  "Orchestral",
  "Vintage",
  "Electronic",
  "Folkish",
  "Lyrics",
  "No lyrics",
  "Epic",
  "Easy",
  "Eccentric",
  "Intense",
  "Smooth",
  "Translucent",
  "Vibrant",
  "Misty",
  "Dark",
];

export const PIECES = [
  {
    name: "I Thought It Would Be Fun",
    tags: ["Piano", "Orchestral", "Vintage"],
    imageSrc: "/images/pieces/track1.webp",
    audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Worn Out",
    tags: ["Piano", "Electronic"],
    imageSrc: "/images/pieces/track2.webp",
    audioSrc: "/audio/Theory-of-Light-Master.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Threat Serenade",
    tags: ["Dark", "Vibrant", "Misty"],
    imageSrc: "/images/pieces/track3.webp",
    audioSrc: "/audio/GOING-FAR-AWAY-_VINTAGE-HARMONY__1_.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "The End of Patience",
    tags: ["Vibrant", "Misty", "Epic"],
    imageSrc: "/images/pieces/track4.webp",
    audioSrc: "/audio/FULL-OF-WONDERING_1__1.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Revival of the Unknown",
    tags: ["Folkish", "Lyrics", "No lyrics", "Epic", "Easy"],
    imageSrc: "/images/pieces/track1.webp",
    audioSrc: "/audio/PIANO-PLAY-MORE-NATURAL.mp3",
    videoSrc: "u0dBG0AL3Cs",
  },
  {
    name: "Power Drip",
    tags: ["Epic", "Easy", "Eccentric"],
    imageSrc: "/images/pieces/track2.webp",
    audioSrc: "/audio/WORN-OUT_1__1",
    videoSrc: "u0dBG0AL3Cs",
  },
];

export const PROJECTS = [
  {
    name: "Project #1",
    description: "TV Drama, 2021",
    tags: ["Film"],
    imageSrc: "/images/projects/project1.webp",
    tracks: [
      {
        name: "I Thought It Would Be Fun",
        tags: ["Piano", "Orchestral", "Vintage"],
        imageSrc: "/images/track1.webp",
        audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Worn Out",
        tags: ["Piano", "Electronic"],
        imageSrc: "/images/track2.webp",
        audioSrc: "/audio/Theory-of-Light-Master.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Threat Serenade",
        tags: ["Dark", "Vibrant", "Misty"],
        imageSrc: "/images/track3.webp",
        audioSrc: "/audio/GOING-FAR-AWAY-_VINTAGE-HARMONY__1_.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
    ],
  },
  {
    name: "Project #2",
    description: "Game, 2022",
    tags: ["Ad"],
    imageSrc: "/images/projects/project2.webp",
    tracks: [
      {
        name: "I Thought It Would Be Fun",
        tags: ["Piano", "Orchestral", "Vintage"],
        imageSrc: "/images/track1.webp",
        audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Worn Out",
        tags: ["Piano", "Electronic"],
        imageSrc: "/images/track2.webp",
        audioSrc: "/audio/Theory-of-Light-Master.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Threat Serenade",
        tags: ["Dark", "Vibrant", "Misty"],
        imageSrc: "/images/track3.webp",
        audioSrc: "/audio/GOING-FAR-AWAY-_VINTAGE-HARMONY__1_.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
    ],
  },
  {
    name: "Project #2",
    description: "TV Commercial, 2019",
    tags: ["Mystery", "Thriller"],
    imageSrc: "/images/projects/project1.webp",
    tracks: [
      {
        name: "I Thought It Would Be Fun",
        tags: ["Piano", "Orchestral", "Vintage"],
        imageSrc: "/images/track1.webp",
        audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Worn Out",
        tags: ["Piano", "Electronic"],
        imageSrc: "/images/track2.webp",
        audioSrc: "/audio/Theory-of-Light-Master.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Threat Serenade",
        tags: ["Dark", "Vibrant", "Misty"],
        imageSrc: "/images/track3.webp",
        audioSrc: "/audio/GOING-FAR-AWAY-_VINTAGE-HARMONY__1_.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
    ],
  },
  {
    name: "Project #2",
    description: "TV Commercial, 2019",
    tags: ["Piano", "Orchestral", "Vintage"],
    imageSrc: "/images/projects/project2.webp",
    tracks: [
      {
        name: "I Thought It Would Be Fun",
        tags: ["Piano", "Orchestral", "Vintage"],
        imageSrc: "/images/track1.webp",
        audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Worn Out",
        tags: ["Piano", "Electronic"],
        imageSrc: "/images/track2.webp",
        audioSrc: "/audio/Theory-of-Light-Master.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Threat Serenade",
        tags: ["Dark", "Vibrant", "Misty"],
        imageSrc: "/images/track3.webp",
        audioSrc: "/audio/GOING-FAR-AWAY-_VINTAGE-HARMONY__1_.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
    ],
  },
  {
    name: "Project #2",
    description: "TV Commercial, 2019",
    tags: ["Comedy", "Action"],
    imageSrc: "/images/projects/project1.webp",
    tracks: [
      {
        name: "I Thought It Would Be Fun",
        tags: ["Piano", "Orchestral", "Vintage"],
        imageSrc: "/images/track1.webp",
        audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Worn Out",
        tags: ["Piano", "Electronic"],
        imageSrc: "/images/track2.webp",
        audioSrc: "/audio/Theory-of-Light-Master.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Threat Serenade",
        tags: ["Dark", "Vibrant", "Misty"],
        imageSrc: "/images/track5.webp",
        audioSrc: "/audio/GOING-FAR-AWAY-_VINTAGE-HARMONY__1_.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
    ],
  },
  {
    name: "Project #2",
    description: "TV Commercial, 2019",
    tags: ["Game", "Fantasy"],
    imageSrc: "/images/projects/project2.webp",
    tracks: [
      {
        name: "I Thought It Would Be Fun",
        tags: ["Piano", "Orchestral", "Vintage"],
        imageSrc: "/images/track1.webp",
        audioSrc: "/audio/Free_Test_Data_2MB_MP3.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Worn Out",
        tags: ["Piano", "Electronic"],
        imageSrc: "/images/track2.webp",
        audioSrc: "/audio/Theory-of-Light-Master.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
      {
        name: "Threat Serenade",
        tags: ["Dark", "Vibrant", "Misty"],
        imageSrc: "/images/track3.webp",
        audioSrc: "/audio/GOING-FAR-AWAY-_VINTAGE-HARMONY__1_.mp3",
        videoSrc: "u0dBG0AL3Cs",
      },
    ],
  },
];

export const NO_TRACKS_FOUND_WARNING =
  "What a peculiar request! Nothing I've made matches yet! For now please try other combos or single tags.";
